/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.optpanegui;

import javax.swing.JOptionPane;

/**
 *
 * @author D-21
 */
public class OptionPaneLatihan extends javax.swing.JFrame {

    /**
     * Creates new form OptionPaneLatihan
     */
    public OptionPaneLatihan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNmessage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BTNerror = new javax.swing.JButton();
        BTNconfirm = new javax.swing.JButton();
        BTNwarning = new javax.swing.JButton();
        BTNplain = new javax.swing.JButton();
        BTNinput = new javax.swing.JButton();
        BTNoption = new javax.swing.JButton();
        BTNinformationmsg = new javax.swing.JButton();
        BTNquestionmsg = new javax.swing.JButton();
        BTNclose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNmessage.setText("Message Dialog");
        BTNmessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNmessageActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Option Pane GUI");

        BTNerror.setText("Error Message");
        BTNerror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNerrorActionPerformed(evt);
            }
        });

        BTNconfirm.setText("Confirm Dialog");
        BTNconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNconfirmActionPerformed(evt);
            }
        });

        BTNwarning.setText("Warning Message");
        BTNwarning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNwarningActionPerformed(evt);
            }
        });

        BTNplain.setText("Plain Message");
        BTNplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNplainActionPerformed(evt);
            }
        });

        BTNinput.setText("Input Dialog");
        BTNinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNinputActionPerformed(evt);
            }
        });

        BTNoption.setText("Option Dialog");
        BTNoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNoptionActionPerformed(evt);
            }
        });

        BTNinformationmsg.setText("Information Message");
        BTNinformationmsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNinformationmsgActionPerformed(evt);
            }
        });

        BTNquestionmsg.setText("Question Message");
        BTNquestionmsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNquestionmsgActionPerformed(evt);
            }
        });

        BTNclose.setText("Close");
        BTNclose.setToolTipText("");
        BTNclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNcloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTNconfirm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNoption))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTNmessage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNinput))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTNwarning)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                                .addComponent(BTNquestionmsg))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTNerror)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNinformationmsg))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTNplain)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BTNclose)
                                .addGap(13, 13, 13)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(BTNplain)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNmessage)
                    .addComponent(BTNinput))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNconfirm)
                    .addComponent(BTNoption))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNerror)
                    .addComponent(BTNinformationmsg))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNwarning)
                    .addComponent(BTNquestionmsg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNclose)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNmessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNmessageActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Ini adalah pesan saya.");
    }//GEN-LAST:event_BTNmessageActionPerformed

    private void BTNerrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNerrorActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Your process cannot be continued", "Did it Error?", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_BTNerrorActionPerformed

    private void BTNconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNconfirmActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(this, "Choose Yes or No To Confirm");
        
        switch(answer) {
            case JOptionPane.YES_OPTION -> JOptionPane.showMessageDialog(this, "You chose Yes");
            case JOptionPane.NO_OPTION -> JOptionPane.showMessageDialog(this, "You chose No");
            case JOptionPane.CANCEL_OPTION -> JOptionPane.showMessageDialog(this, "You Canceled");
        }
    }//GEN-LAST:event_BTNconfirmActionPerformed

    private void BTNwarningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNwarningActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Please fill your information", "Warning Message", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_BTNwarningActionPerformed

    private void BTNplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNplainActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(this, "Ini adalah pesan yang ingin saya sampaikan.", "Just a Plain Message", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_BTNplainActionPerformed

    private void BTNinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNinputActionPerformed
        // TODO add your handling code here:
        String inputmsg = JOptionPane.showInputDialog("Please Input Something: ");
        JOptionPane.showConfirmDialog(this, "You've inputted " + inputmsg);
    }//GEN-LAST:event_BTNinputActionPerformed

    private void BTNoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNoptionActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showOptionDialog(this, "Do you want to Exit?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(answer == JOptionPane.YES_NO_OPTION) {
            JOptionPane.showMessageDialog(this, "The Program will Close.");
            System.exit(0);
        }
    }//GEN-LAST:event_BTNoptionActionPerformed

    private void BTNinformationmsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNinformationmsgActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Please Input a Valid Information", "Information Message", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BTNinformationmsgActionPerformed

    private void BTNquestionmsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNquestionmsgActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Are you sure to exit from this Program?", "Question Message", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_BTNquestionmsgActionPerformed

    private void BTNcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNcloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BTNcloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionPaneLatihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionPaneLatihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionPaneLatihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionPaneLatihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionPaneLatihan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNclose;
    private javax.swing.JButton BTNconfirm;
    private javax.swing.JButton BTNerror;
    private javax.swing.JButton BTNinformationmsg;
    private javax.swing.JButton BTNinput;
    private javax.swing.JButton BTNmessage;
    private javax.swing.JButton BTNoption;
    private javax.swing.JButton BTNplain;
    private javax.swing.JButton BTNquestionmsg;
    private javax.swing.JButton BTNwarning;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
